<?php
/**
 * @file
 */

/*
 * implement hook_init.
 */
function realty_init(){
  if(current_path() == '<front>'){
    drupal_goto('taxonomy/term/1');
  }
}

/**
 * @param $name
 * @return array
 */

function realty_get_list_city(){
  $vid = taxonomy_vocabulary_machine_name_load('cities');
  return $terms = taxonomy_get_tree($vid->vid, 0, NULL, TRUE);
}

function realty_get_areas_current_city(){

  $city = menu_get_object('taxonomy_term', 2);
  $view = views_get_view('search');
  $view->set_display('search_area');
  $view->display_handler->options['filters']['field_area_city_tid']['value'] = $city->tid;
  $view->pre_execute(array());
  $view->display_handler->preview();
  $view->post_execute();
  foreach($view->result as $value) {
    $area_option[$value->tid] = $value->taxonomy_term_data_name;
  }
  return $area_option;
}

/**
 * Form builder for search form.
 */
function realty_search_form($form, $form_state){
  $area_option = realty_get_areas_current_city();
  $node = new stdClass();
  $node->type = 'apartament';
  node_object_prepare($node);

  $form['area'] = array(
    '#type'=>'select',
    '#title'=>'Area',
    '#options'=> $area_option,
  );

  $form['floor'] = array(
    '#type'=>'textfield',
    '#title'=>'floor',
    '#attributes'=>array(
      'size' => 2,
      'maxlength' => 2,
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Reserve'),
  );
  $form['#theme'][] = 'search_form';
  return $form;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function realty_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels') {
    return "plugins/$plugin_type";
  }

  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return "plugins/content_types";
  }
}