<?php
/**
 * @file
 */

/*
 * implement hook_init.
 */
function realty_init(){
  if(current_path() == '<front>'){
    drupal_goto('taxonomy/term/1');
  }
}

/*
 * implement hook_menu.
 */
function realty_menu(){
  $item['get_developer_complex'] = array(
    'title' => 'complex',
    'page callback' => 'realty_get_developer_complex',
    'access callback' => TRUE,
  );
  return $item;
}

/**
 * @param $name
 * @return array
 */

function realty_get_list_city(){
  $vid = taxonomy_vocabulary_machine_name_load('cities');
  return $terms = taxonomy_get_tree($vid->vid, 0, NULL, TRUE);
}

/*
 *Page callback to /get_developer_complex.
 */
function realty_get_developer_complex(){
  $complexs = realty_get_complex_current_city($_POST['developer'], $_POST['developer']);
  foreach($complexs as $key => $complex ){
    print "<option value=". $key .">". $complex ."</option>";
  }
}

/**
 * Get areas the current city
 */
function realty_get_areas_current_city(){

  $city = menu_get_object('taxonomy_term', 2);
  $view = views_get_view('search');
  $view->set_display('search_area');
  $view->display_handler->options['filters']['field_area_city_tid']['value'] = $city->tid;
  $view->pre_execute(array());
  $view->display_handler->preview();
  $view->post_execute();
  foreach($view->result as $value) {
    $area_option[$value->tid] = $value->taxonomy_term_data_name;
  }
  return $area_option;
}

/**
 * Get developers the current city
 */
function realty_get_developer_current_city(){
  $city_id = menu_get_object('taxonomy_term', 2);
  $view = views_get_view('term_view');
  $view->set_display('developers');
  $view->pre_execute(array());
  $view->display_handler->preview();
  $view->post_execute();
  $developer_option[$city_id->tid] = 'Any';
  foreach($view->result as $value) {
    $developer_option[$value->tid] = $value->_field_data['tid']['entity']->name;
  }
  return $developer_option;
}

/**
 * Get complex the current city
 */
function realty_get_complex_current_city($tid = 0, $city = 0){

  $view = views_get_view('complex');
  if($tid != 0 && $city == 0) {
    $view->set_display('complex_developer');
    $view->display_handler->options['arguments']['tid']['default_argument_options']['argument'] = $tid;
  }
  else {
    $view->set_display('complexs');
    if($city != 0) {
      $view->display_handler->options['arguments']['tid']['default_argument_options']['term_page'] = $city;
    }
  }
  $view->pre_execute(array());
  $view->display_handler->preview();
  $view->post_execute();
  foreach($view->result as $value) {
    $complex_option[$value->nid] = $value->node_title;
  }
  return $complex_option;
}

/**
 * Form builder for search form.
 */
function realty_search_form($form, $form_state){
  $area_option = realty_get_areas_current_city();
  $developer_option = realty_get_developer_current_city();
  $complex_option = realty_get_complex_current_city();
  $room_option = array(
    '1'=>'1 комната',
    '2'=>'2 комнаты',
    '3'=>'3 комнаты',
    '4'=>'4 комнаты',
  );

  $form['area'] = array(
    '#type'=>'select',
    '#title'=>'Area',
    '#options'=> $area_option,
  );

  $form['floor'] = array(
    '#type'=>'textfield',
    '#title'=>'floor',
    '#attributes'=>array(
      'size' => 2,
      'maxlength' => 2,
    ),
  );

  $form['room'] = array(
    '#type'=>'select',
    '#title'=>'Number of room',
    '#options'=> $room_option,
  );

  $form['sq_from'] = array(
    '#type'=>'textfield',
    '#title'=>'Sq from',
    '#attributes'=>array(
      'size' => 4,
      'maxlength' => 5,
    ),
  );

  $form['sq_to'] = array(
    '#type'=>'textfield',
    '#title'=>'Sq to',
    '#attributes'=>array(
      'size' => 4,
      'maxlength' => 5,
    ),
  );

  $form['price_from'] = array(
    '#type'=>'textfield',
    '#title'=>'Price from',
    '#attributes'=>array(
      'size' => 4,
      'maxlength' => 5,
    ),
  );

  $form['price_to'] = array(
    '#type'=>'textfield',
    '#title'=>'Price to',
    '#attributes'=>array(
      'size' => 4,
      'maxlength' => 5,
    ),
  );

  $form['parking'] = array(
    '#type'=>'checkbox',
    '#title'=>'Parking',
  );

  $form['coast_from'] = array(
    '#type'=>'textfield',
    '#title'=>'Coast from',
    '#attributes'=>array(
      'size' => 7,
      'maxlength' => 10,
    ),
  );

  $form['coast_to'] = array(
    '#type'=>'textfield',
    '#title'=>'Coast to',
    '#attributes'=>array(
      'size' => 7,
      'maxlength' => 10,
    ),
  );

  $form['developer'] = array(
    '#type'=>'select',
    '#title'=>'Developer',
    '#options'=> $developer_option,
  );

  $form['complex'] = array(
    '#type'=>'select',
    '#title'=>'Complex',
    '#options'=> $complex_option,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Reserve'),
  );

  $form['#theme'][] = 'search_form';
  return $form;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function realty_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels') {
    return "plugins/$plugin_type";
  }

  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return "plugins/content_types";
  }
}