<?php
 
function smart_ip_ipgeobase_source_smart_ip_get_location_alter(&$result) {
  $smart_ip_source = variable_get('smart_ip_source', 'ipinfodb_service');
  if ($smart_ip_source == 'ipgeobase.ru') {
    $ip_address = $result['ip_address'];
    //krumo($ip_address);
    $long_ip = sprintf('%u', ip2long($ip_address));
    // TODO Explain this query.
    $query = db_select('smart_ip_ipgeobase_source_blocks', 'ipb')
      ->fields('ipb', array('country'))
      ->fields('ipr', array('rid', 'city', 'subject', 'fo'))
      ->condition('begin', $long_ip, '<=')
      ->condition('end', $long_ip, '>=')
      ->orderBy('begin', 'DESC')
      ->range(0, 1);
    $query->leftJoin('smart_ip_ipgeobase_source_regions', 'ipr', 'ipb.rid = ipr.rid');
    $ip_obj = $query->execute()->fetch();
    $countries = country_get_list();
    $result['country_code'] = $ip_obj->country;
    $result['country']      = empty($result['country_code']) ? '' : $countries[$result['country_code']];
    $result['region']       = $ip_obj->subject;
    $result['region_code']  = $ip_obj->rid;
    $result['city']         = $ip_obj->city;
    $result['zip']          = '';
    $result['latitude']     = '';
    $result['longitude']    = '';
    $result['time_zone']    = '';
  }
}

/**
 * Implements hook_form_alter()
 */
function  smart_ip_ipgeobase_source_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'smart_ip_admin_settings') {
    $form['smart_ip_source_selection']['smart_ip_source']['#options']['ipgeobase.ru'] = t('Use data from ipgeobase.ru, stored in local database');
  }
}

